### ISSUE TITLE
Cursor, not selection, used as target

### ISSUE THREAD

**Issue by dlio** [robhurring/atom-change-case#29] opened 2016-04-22 22:06 UTC
Unable to apply change-case actions to more than one word at a time.

Atom version 1.6.0
change-case version 0.6.0

Please advise.

Thanks for the plugin!

**Comment by cage1016** [comment] 2016-04-29 02:09
same issus

Atom    : 1.7.3
change-case@0.6.0

**Comment by mliq** [comment] 2016-06-13 16:04
same - can't change multiple words to title case... kind of removes the usefulness.

**Comment by deiga** [comment] 2016-07-04 13:34
Can you give an example on how this is not working? I can't reproduce with Atom 1.8.0 and change-case 0.6.0

**Comment by mliq** [comment] 2016-07-18 17:22
1. type multiple lowercase words
2. select them
3. execute Change Case: title in command palette.

behavior: only the word near cursor is changed.
expected: all selected words are changed.

**Comment by deiga** [comment] 2016-07-21 15:10
This should now be fixed in 0.6.2

**Closed by deiga** 2016-07-21 15:10 UTC
